#!/usr/bin/env bash
# Regenerate per-tool agent instruction files from the canonical doctrine.
# Edit .claude/DOCTRINE.md (and the *-supplement.md files), then run this.
# Claude Code's CLAUDE.md is intentionally NOT generated — it is maintained by
# hand and DOCTRINE.md is kept as its canonical mirror.
set -euo pipefail

DOTFILES="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCTRINE="$DOTFILES/.claude/DOCTRINE.md"
HEADER="<!-- GENERATED by ~/.dotfiles/sync-agents.sh from .claude/DOCTRINE.md + this tool's supplement. Do not hand-edit; edit the source and re-run. -->"

gen() {
  local out="$1" supplement="$2"
  [[ -f "$out" ]] && cp -f "$out" "$out.bak.$(date +%Y%m%d-%H%M%S)"
  { printf '%s\n\n' "$HEADER"; cat "$DOCTRINE"; printf '\n'; cat "$supplement"; } > "$out"
  echo "wrote $out"
}

# Codex CLI
gen "$HOME/.codex/AGENTS.md" "$DOTFILES/.claude/codex-supplement.md"
