#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[ui]
default-command = "log"

[user]
name = "Jacob Sanderson"
email = "jacob@jacobdevelops.com"

[gg.ui]
recent-workspaces = ["/home/jacob/Documents/Developer/aston-api", "/home/jacob/Documents/Developer/numen"]
