[tools]
air = "latest"
argocd = "latest"
"asdf:asdf-community/asdf-bitwarden-secrets-manager" = "latest"
aws = { version = "latest", symlink_bins = "true" }
bazelisk = "latest"
biome = "latest"
bun = "latest"
cocoapods = { version = "latest", os = ["macos"] }
direnv = "latest"
doppler = "latest"
duckdb = "latest"
firebase = "latest"
gemini = "latest"
gh = "latest"
go = "latest"
golangci-lint = "latest"
heroku = "latest"
helm = "latest"
hurl = "latest"
hyperfine = "latest"
java = "latest"
jj = "latest"
jjui = "latest"
just = "latest"
mysql = "latest"
node = "latest"
pipx = "latest"
pnpm = "latest"
postgres = "latest"
python = "latest"
railway = { version = "latest", exe = "railway" }
ruby = "latest"
sentry = "latest"
sqlite = "latest"
stripe = "latest"
task = "latest"
terraform = "latest"
terraformer = "latest"
usage = "latest"
uv = "latest"
vercel = "latest"
yq = "latest"
"github:rabbitmq/rabbitmqadmin-ng" = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node"]

[settings.node]
gpg_verify = false
